conosle.error(Halp!)
console.warn(Please Stop!)
console.log (Take a break)
console.error(Halp!) , console.warn(Please stop) , console.log (Take a break)
console.warn("Please stop!")
console.log("I am a logger")
